In [1]:
import statistics


grades = [85, 93, 45, 89, 85]
sum(grades) / len(grades)

statistics.median(grades)
statistics.mode(grades)
statistics.mean(grades)

79.4

In [2]:
### NumPy

import numpy as np 
numbers = np.array([2, 3, 5, 7, 11]) 
numbers

array([ 2,  3,  5,  7, 11])

In [3]:
type(numbers)

numpy.ndarray

In [4]:
## array multidimensionali
multidim_arr = np.array([[1, 2, 3], [4, 5, 6]])
multidim_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
## dtype

integers = np.array([[1, 2, 3], [4, 5, 6]])
integers.dtype

dtype('int64')

In [6]:
floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])
floats.dtype

dtype('float64')

In [7]:
## ndim e shape
print("ndim: per integers: ", integers.ndim)
print("ndim per floats: ", floats.ndim)

print("shape: per integers: ", integers.shape)
print("shape per floats: ", floats.shape)




ndim: per integers:  2
ndim per floats:  1
shape: per integers:  (2, 3)
shape per floats:  (5,)


In [8]:
## size e itemsize

print(integers.size)
print(integers.itemsize)  # 4 if C compiler uses 32-bit ints
print(floats.size)
print(floats.itemsize)



6
8
5
8


In [9]:
## iterate over arrays
print("uso classico di iterare su array")
for row in integers:
    for column in row:
        print(column, end=' ')
    print()
print("sfrutto l'attributo flat")

for el in integers.flat:
    print(el)
    


uso classico di iterare su array
1 2 3 
4 5 6 
sfrutto l'attributo flat
1
2
3
4
5
6


In [10]:
## filling up arrays. zeros, ones, full 

zeros_array = np.zeros(5)
ones_array = np.ones((2, 4), dtype=int)
full_array = np.full((3, 5), 13)

zeros_array

array([0., 0., 0., 0., 0.])

In [11]:
ones_array

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [12]:
full_array

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

In [17]:
## arange

np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [19]:
np.arange(10, 1, -2)

array([10,  8,  6,  4,  2])

In [20]:
## linspace
np.linspace(0.0, 1.0)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [21]:
## reshape

array_to_reshape = np.arange(1, 21)
print("before reshaping\n", array_to_reshape)
array_to_reshape = array_to_reshape.reshape(4, 5)
print("after reshaping\n", array_to_reshape)

before reshaping
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
after reshaping
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [22]:
## operators e array


numbers = np.arange(1, 6)
print(numbers * 2)
print(numbers ** 3)

numbers2 = np.linspace(1.1, 5.5, 5)
print(numbers * numbers2)

print(numbers >= 13)
print(numbers2 < numbers)
print(numbers == numbers2)
print(numbers == numbers)





[ 2  4  6  8 10]
[  1   8  27  64 125]
[ 1.1  4.4  9.9 17.6 27.5]
[False False False False False]
[False False False False False]
[False False False False False]
[ True  True  True  True  True]


In [6]:
"""
Esercizio:
Given the following array:
array([[ 1, 2, 3, 4, 5], [6, 7, 8, 9,10],
              [11, 12, 13, 14, 15]])
write statements to perform the following tasks:
a) Select the second row.
b) Select the first and third rows.
c) Select the middle three columns.
"""

import numpy as np
a = np.arange(1, 16).reshape(3, 5)
print(a)
print("a", a[1])
print("b", a[[0, 2]])
print("c", a[:, 1])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
a [ 6  7  8  9 10]
b [[ 1  2  3  4  5]
 [11 12 13 14 15]]
c [ 2  7 12]


In [10]:
### reshaping and transposing
import numpy as np
grades = np.array([[87, 96, 70], [100, 87, 90]])
print(grades)

grades.reshape(1, 6)
print(grades)

## resize modifica la forma iniziale dell'array
grades.resize(1, 6)
print(grades)

## flatten, fa un copia profonda!
flattened = grades.flatten()
print(flattened)
print(grades)

## ravel, fa un vista (copia superficiale)
raveled = grades.ravel()
print(raveled)

## trasposta
print(grades.T)

[[ 87  96  70]
 [100  87  90]]
[[ 87  96  70]
 [100  87  90]]
[[ 87  96  70 100  87  90]]
[ 87  96  70 100  87  90]
[[ 87  96  70 100  87  90]]
[ 87  96  70 100  87  90]
[[ 87]
 [ 96]
 [ 70]
 [100]
 [ 87]
 [ 90]]
